// styles.js
const styles = {
  app: {
    background: "#fafafa",
    color: "#333",
    minHeight: "100vh",
    fontFamily: "'Inter', system-ui, sans-serif",
    lineHeight: 1.6,
  },
  header: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    padding: "24px 32px",
    background: "#fff",
    borderBottom: "1px solid #e5e5e5",
    position: "sticky",
    top: 0,
    zIndex: 10,
  },
  nav: {
    display: "flex",
    alignItems: "center",
    gap: "32px",
    fontSize: "14px",
    fontWeight: 500,
  },
  navIcon: {
    fontSize: "20px",
  },
  navLink: {
    color: "#666",
    textDecoration: "none",
    cursor: "pointer",
    transition: "color 0.2s",
  },
  hero: {
    background: "#fff",
    padding: "64px 32px",
    textAlign: "center",
    position: "relative",
  },
  heroContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    maxWidth: "800px",
    margin: "0 auto",
    gap: "48px",
  },
  illustration: {
    display: "flex",
    justifyContent: "center",
  },
  illustrationSvg: {
    width: "180px",
    height: "220px",
    color: "#000",
  },
  heroSubtitle: {
    fontSize: "16px",
    color: "#666",
    margin: 0,
  },
  heroTitle: {
    fontSize: "48px",
    fontWeight: 700,
    lineHeight: 1.1,
    margin: 0,
    letterSpacing: "-0.02em",
  },
  page: {
    padding: "80px 32px",
    textAlign: "center",
    maxWidth: "800px",
    margin: "0 auto",
  },
  pageTitle: {
    fontSize: "48px",
    fontWeight: 700,
    marginBottom: "16px",
  },
  pageContent: {
    fontSize: "18px",
    color: "#666",
  },
  panel: {
    background: "#fff",
    padding: "48px 40px",
    borderRadius: "24px",
    maxWidth: "1000px",
    margin: "0 auto 48px",
    boxShadow: "0 20px 40px rgba(0,0,0,0.06)",
    border: "1px solid #f0f0f0",
  },
  sectionTitle: {
    fontSize: "13px",
    fontWeight: "600",
    color: "#64748b",
    marginBottom: "20px",
    marginTop: "0",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    gridColumn: "1 / -1",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "24px",
    marginBottom: "32px",
  },
  fullWidth: {
    gridColumn: "1 / -1",
  },
  input: {
    width: "100%",
    padding: "16px 20px",
    marginBottom: "0",
    background: "#f8fafc",
    color: "#0f172a",
    border: "1px solid #e2e8f0",
    borderRadius: "12px",
    fontSize: "15px",
    fontWeight: "500",
    outline: "none",
    transition: "all 0.2s cubic-bezier(0.4, 0, 0.2, 1)",
    boxSizing: "border-box",
  },
  select: {
    width: "100%",
    padding: "16px 20px",
    marginBottom: "0",
    background: "#f8fafc",
    color: "#0f172a",
    border: "1px solid #e2e8f0",
    borderRadius: "12px",
    fontSize: "15px",
    fontWeight: "500",
    cursor: "pointer",
    appearance: "none",
    backgroundImage: "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%2364748b' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='m6 8 4 4 4-4'/%3e%3c/svg%3e\")",
    backgroundPosition: "right 16px center",
    backgroundRepeat: "no-repeat",
    backgroundSize: "16px",
    paddingRight: "48px",
    boxSizing: "border-box",
    transition: "all 0.2s",
  },
  row: { // Kept for backwards compatibility if needed, though grid replaces it mostly
    display: "flex",
    gap: "20px",
    marginBottom: "20px",
  },
  col: {
    flex: 1,
  },
  colorWrapper: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    background: "#f8fafc",
    padding: "12px 16px",
    borderRadius: "12px",
    border: "1px solid #e2e8f0",
    height: "54px", // match input height
    boxSizing: "border-box",
  },
  colorInput: {
    border: "none",
    width: "32px",
    height: "32px",
    padding: 0,
    background: "transparent",
    cursor: "pointer",
    borderRadius: "8px",
  },
  colorValue: {
    fontSize: "14px",
    color: "#64748b",
    fontFamily: "monospace",
    flex: 1,
  },
  label: {
    marginBottom: "8px",
    display: "block",
    fontSize: "13px",
    color: "#64748b",
    fontWeight: 600,
  },
  fileInput: {
    width: "100%",
    padding: "16px 20px",
    marginBottom: "0",
    background: "#f8fafc",
    color: "#333",
    border: "1px solid #e2e8f0",
    borderRadius: "12px",
    fontSize: "14px",
    boxSizing: "border-box",
  },
  button: {
    marginTop: "12px",
    width: "100%",
    padding: "20px",
    background: "linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)",
    border: "none",
    color: "#fff",
    fontWeight: 600,
    borderRadius: "14px",
    cursor: "pointer",
    fontSize: "16px",
    transition: "all 0.2s cubic-bezier(0.4, 0, 0.2, 1)",
    boxShadow: "0 10px 20px -10px rgba(79, 70, 229, 0.5)",
    letterSpacing: "0.01em",
  },
  gallery: {
    marginTop: "48px",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: "32px",
    padding: "0 32px",
    maxWidth: "1200px",
    marginLeft: "auto",
    marginRight: "auto",
  },
  card: {
    background: "#fff",
    padding: "32px",
    borderRadius: "16px",
    boxShadow: "0 8px 32px rgba(0,0,0,0.08)",
    border: "1px solid #e5e5e5",
  },
  cardTitle: {
    fontSize: "20px",
    fontWeight: 600,
    marginBottom: "20px",
    color: "#333",
  },
  image: {
    width: "100%",
    borderRadius: "12px",
    marginTop: "12px",
  },
};

export default styles;